 language: node_js
 node_js:
   - "0.10"
before_install: npm install -g grunt-cli
install: npm install
before_script: grunt
notifications:
  email: false
deploy:
  provider: heroku
  api_key: "404ff284-b522-4ee5-99bf-99b54e32a66a"
  app: "powerful-cove-3241"
